name: deploye-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
  pull_request:

defaults:
  run:
    working-directory: auth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
      
      - name: Build application
        run: npm run build

      - name: Deploye to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws configure set default.region us-east-1
          aws s3 sync './dist/' s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest --acl public-read --follow-symlinks --delete --exclude '.git*/*'

      - name: Invalidate file From Cloud Front
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/auth/latest/remoteEntry.js"