name: deploye-container

on:
  push:
    branches:
      - main
    paths:
      - 'container/**'
  pull_request:

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build applicaton
        run: npm run build

      - name: Deploy to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_ec2_metadata_disabled true
          aws s3 sync './container/dist/' s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest --acl public-read --follow-symlinks --delete --exclude '.git*/*'


